[package]
name = "rust-tinyraytracer"
version = "0.1.0"
authors = ["zhen"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.17.*"
